# Generated by Django 5.1.3 on 2024-11-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComidaRapida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Hamburguesas', 'Hamburguesas'), ('Pizzas', 'Pizzas'), ('Bebidas', 'Bebidas'), ('Postres', 'Postres')], default='Hamburguesas', max_length=50)),
                ('precio', models.PositiveIntegerField()),
                ('ingredientes', models.TextField()),
                ('tamanio', models.CharField(choices=[('Chico', 'Chico'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], default='Mediano', max_length=20)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
