# Generated by Django 5.1.3 on 2024-11-24 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comidarapida',
            name='categoria',
            field=models.CharField(choices=[('Hamburguesas', 'Hamburguesas'), ('Pizzas', 'Pizzas'), ('Bebidas', 'Bebidas'), ('Postres', 'Postres')], default='Hamburguesas', max_length=50, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='comidarapida',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='¿Disponible?'),
        ),
        migrations.AlterField(
            model_name='comidarapida',
            name='ingredientes',
            field=models.TextField(help_text='Ejemplo: Carne, queso, tomate, lechuga', verbose_name='Ingredientes Principales'),
        ),
        migrations.AlterField(
            model_name='comidarapida',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del Producto'),
        ),
        migrations.AlterField(
            model_name='comidarapida',
            name='precio',
            field=models.PositiveIntegerField(verbose_name='Precio (CLP)'),
        ),
        migrations.AlterField(
            model_name='comidarapida',
            name='tamanio',
            field=models.CharField(choices=[('Chico', 'Chico'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], default='Mediano', max_length=20, verbose_name='Tamaño'),
        ),
    ]
