# Generated by Django 5.1.3 on 2024-11-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0002_alter_comidarapida_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comidarapida',
            name='tamanio',
            field=models.CharField(choices=[('Chico', 'Chico'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], default='Mediano', max_length=200, verbose_name='Tamaño'),
        ),
    ]
